version: '2'
services:
  zookeeper:
    container_name: frosconzookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: frosconkafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 60000
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 240000
      KAFKA_MIN_CLEANABLE_DIRTY_RATIO: 0.01
      KAFKA_LOG_CLEANER_ENABLE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
